name: E2E Tests

on:
  push:
    branches:
      - e2e
  pull_request:
    branches:
      - e2e

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: stream-query
          MYSQL_DATABASE: stream-query
          MYSQL_USER: stream-query
          MYSQL_PASSWORD: stream-query
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -u stream-query --password=stream-query --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      postgres:
        image: postgres
        env:
          POSTGRES_DB: stream-query
          POSTGRES_USER: stream-query
          POSTGRES_PASSWORD: stream-query
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U stream-query"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build with Maven
        run: mvn -B -X package --file pom.xml

      - name: Run H2 Tests (Default)
        run: mvn -B -X test

      - name: Execute MySQL schema and data scripts
        run: |
          mysql -h 127.0.0.1 -P 3306 -u stream-query --password=stream-query stream-query < ./stream-plugin/stream-plugin-mybatis-plus/src/test/resources/sql/mysql/schema.sql
          mysql -h 127.0.0.1 -P 3306 -u stream-query --password=stream-query stream-query < ./stream-plugin/stream-plugin-mybatis-plus/src/test/resources/sql/mysql/data.sql
        if: success()

      - name: Run MySQL Tests
        run: mvn -B -X test -Dspring.profiles.active=mysql
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/stream-query?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
          SPRING_DATASOURCE_USERNAME: stream-query
          SPRING_DATASOURCE_PASSWORD: stream-query

      - name: Execute PostgreSQL schema and data scripts
        run: |
          PGPASSWORD=stream-query psql -h localhost -U stream-query -d stream-query -p 5432 -a -f ./stream-plugin/stream-plugin-mybatis-plus/src/test/resources/sql/pgsql/schema.sql
          PGPASSWORD=stream-query psql -h localhost -U stream-query -d stream-query -p 5432 -a -f ./stream-plugin/stream-plugin-mybatis-plus/src/test/resources/sql/pgsql/data.sql
        if: success()

      - name: Run PostgreSQL Tests
        run: mvn -B -X test -Dspring.profiles.active=pgsql
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/stream-query
          SPRING_DATASOURCE_USERNAME: stream-query
          SPRING_DATASOURCE_PASSWORD: stream-query
